question_tuple = [
("History of the Medieval Exchequer in Ireland", "Medieval Exchequer"),
("Reforms introduced by King Henry II in Ireland", "King Henry II"),
("Significance of Irish Chancery Letters", "Irish Chancery Letters"),
("Functions of the Royal Treasury in medieval Ireland", "Royal Treasury"),
("Role of Medieval Dublin Castle in governance", "Medieval Dublin Castle"),
("VRIT digital archives project overview", "VRIT"),
("Challenges of Governance in historical Ireland", "Challenges of Governance"),
("Exploring the Virtual Record Treasury of Ireland", "Virtual Record Treasury of Ireland"),
("Quakers in Irish religious history", "Quakers"),
("Conditions in the Oughterard Workhouse", "Oughterard Workhouse"),
("Overview of the Irish Poor Law system", "Irish Poor Law"),
("CIRCLE project and Irish Chancery records", "CIRCLE"),
("Impact of the Cromwellian Surveys on Irish land", "Cromwellian Surveys"),
("Analysis of the 1766 Religious Census in Ireland", "1766 Religious Census"),
("History of Newchapel in Ireland", "Newchapel"),
("Archives and collections at Trinity College Dublin", "Trinity College Dublin"),
("Herbert Wood and Irish archival contributions", "Herbert Wood"),
("Use of Extended Reality in historical research", "Extended Reality"),
("Policies of King Henry III in Ireland", "King Henry III"),
("Irish House and legislative history", "Irish House"),
("Political role of Lord Salisbury in Irish affairs", "Lord Salisbury"),
("Military history of the 112th Regiment", "112th Regiment"),
("Biography of Edward Trevor and his influence", "Edward Trevor"),
("Contents of the Patent Roll 1 Henry IV", "Patent Roll 1 Henry IV"),
("Edward I’s involvement in Irish governance", "Edward I")
]